info:
  component: Product

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
    port: 7072

management:
  port: 8072

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
    client:
        serviceUrl:
             defaultZone: http://localhost:8761/eureka/
