info:
  component: Product

server:
    port: 7072

management:
  port: 8072
  security:
    enabled: false

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
    client:
        serviceUrl:
             defaultZone: http://localhost:8761/eureka/
