info:
  component: Turbine

PREFIX:
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: ${PORT:7003}

management:
  port: 7033

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        non-secure-port: ${PORT:7003}
    client:
        serviceUrl:
            # defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/
            defaultZone: http://localhost:8761/eureka/

---
spring:
    profiles: cloud
management:
    port: -1

