info:
  component: Turbine

management:
  port: 8003
  security:
    enabled: false

turbine:
  stream:
    port: 8989

spring:
 rabbitmq:
   host: localhost
   port: 5672
   username: guest
   password: guest

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    org.springframework.integration: DEBUG

eureka:
    client:
        serviceUrl:
             defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud